# Configuration for processing ROS2 bag files
# This file specifies the paths, storage format, and topics to extract from the ROS bag.

# Path to the input ROS2 bag file
bag_path: "<bagpath>"

# Directory where the exported data will be saved
output_dir: "<outfolder>"


# Storage format for the exported data. Options are "sqlite3" or "mcap"
storage_id: "sqlite3"

# start time in [s]
#start_time: 1738246906.5

# List of topics to extract from the ROS2 bag
topics:
  # Configuration for the RGB image topic
  - name: "<cam0_topic>"    # Name of the topic to extract
    type: "Image"               # Data type of the topic
    encoding: "bayer_rggb8"            # Encoding format for the image
    sample_interval: <1>          # Write one sample every 3 messages

  # Configuration for the RGB image topic
  - name: "<cam1_topic>"    # Name of the topic to extract
    type: "Image"               # Data type of the topic
    encoding: "bayer_rggb8"            # Encoding format for the image
    sample_interval: <1>          # Write one sample every 3 messages

  # Configuration for the IMU (Inertial Measurement Unit) topic
  - name: "<imu_topic>"              # Name of the topic to extract
    type: "IMU"                     # Data type of the topic
    sample_interval: 1             # Write one sample every 1 messages
